application: jamendogame
version: 1
runtime: python
api_version: 1

handlers:


- url: /res
  static_dir: res

- url: /favicon.ico
  static_dir: /

- url: /ajax
  script: ajax.py
  
- url: /([/a-z]*)
  script: index.py